service: sls-kinesis-streams

useDotenv: true


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  memorySize: 300
  timeout: 10
  architecture: x86_64
  stackTags:
    product: datateam
    env: qa
    created-date: 2022-04-05
    team: data
    customer-impact: false
    terraform: false


functions:
  lambda:
    handler: lambda_function.lambda_handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - KinesisDataStreams
              - Arn


resources:
  Resources:
    KinesisDataStreams:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:StreamName}
        RetentionPeriodHours: ${env:RetentionPeriodHours}
        StreamModeDetails:
          StreamMode: ON_DEMAND
