stages:
  - deploy

dev:
  stage: deploy
  image: node:latest
  when: manual
  only:
    - main
  before_script:
    - echo "My First CICD pipeline "
    - echo  "$NAME"
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli --upgrade --user
    - serverless config credentials --provider aws --key "$AWS_ACCESS_KEY_ID"  --secret "$AWS_SECRET_ACCESS_KEY" -o
  script:
    - sls deploy
  environment: dev
