org: scientist1995
app: demo
service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    apiKeys:
      - name: 'user1'
      - value: 'your-api-key-that-is-at-least-20-characters-long'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
          private: true