org: scientist1995
app: demo
console: true
service: aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    apiKeys:
      - name: 'user1'
        value: 'your-api-key-that-is-at-least-20-characters-long'
        # - user1

plugins:
  - serverless-api-gateway-throttling

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
          private: true