service: sls-pandas-py

provider:
  name: aws
  runtime: python3.6

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  # exclude everything...
  exclude:
    - '**/*'
  include:
    - '*.py'
functions:
  hello:
    handler: handler.hello