service: layer-numpy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: python-numpy
      description: "Layer which contains numpy library"
      compatibleRuntimes:
        - python3.8