
dispatcher:
  handler: dispatcher.dispatch
  events:
    - sns:
        arn:
          Fn::Join:
            - ':'
            - - 'arn:aws:sns'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'MyCustomTopic'
        topicName: MyCustomTopic

